config/routes.rb
Rainforest::Application.routes.draw do
  resources :reviews

  resources :products
  resources :users        # Consider we may not want an "index" action here.
  resources :sessions, only: [:new, :destroy, :create]     # We probably only want create and destroy

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price_in_cents, :price_in_dollars

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}
  validates :price_in_dollars, :numericality => { greater_than: 0 }

  has_many :reviews

  def price_in_dollars
    if self.price_in_cents?
     self.price_in_cents.to_f / 100.0
    end
  end

  def price_in_dollars=(dollars)
    if dollars.present?
     self.price_in_cents = (dollars.to_f * 100).to_i
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  attr_accessible :comment, :product_id, :user_id

  validates :comment, :product, :user, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # There is a lot of magic going on in `has_secure_password` below:
  #
  #  - Creates attribute accessors for password and password_confirmation
  #  - Adds a validation to ensure password == password_confirmation
  #  - Before saving, hashes password and stores it in password_digest

  has_secure_password
  
  attr_accessible :email, :name, :password, :password_confirmation
  validates :name, :presence => true
  validates :email, { :presence => true, :uniqueness => true }
  validates :password, { :presence => true, on: :create }

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    #User.where(:user_id => session[:user_id]).first
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  def create
    @product = Product.new(params[:product])

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /products/1
  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /products/1
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_url
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # The "find_by_email" method is gone in Rails 4
    user = User.where(:email => params[:email]).first

    # Ensure a user was returned, and if so, try to auth. them
    # "has_secure_password" defines authenticate on the model.
    if user && user.authenticate(params[:password])

      # The "session" hash automatically stores cookies in
      # the user's browser. It persists for some time like 2 days.
      session[:user_id] = user.id
      redirect_to products_url, alert: "You are now signed in."
    else
      flash.now[:alert] = "Username or password did not match. Try again."
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to products_path, alert: "You have been signed out."

    # how would they do that? NOt sure what you mean by scrweing with
    # the userid?


  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to products_path, notice: "You are now signed up."
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_price(product)
    number_to_currency product.price_in_dollars
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:alert] %>
    <strong><%= flash[:alert] %></strong>
  <% end %>

  <p>
    <% if current_user %>
      Signed in as <%= current_user.email %>.
      <%= link_to 'Log out', session_path(current_user), method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_session_path %>
      or
      <%= link_to "sign up", new_user_path %>
    <% end %>
  </p>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_dollars %><br />
    <%= f.text_field :price_in_dollars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_reviews.html.erb
<h3>Reviews</h3>

<h4>Reviews for <%= @product.name %></h4>

<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    <em> by <%= review.user.name %> (<%= review.user.created_at.strftime("%b %d %Y  %l:%M %p") %>)</em>
  </p>
<% end %>

<h4>Post a review</h4>

<% if current_user %>
  <%= render 'reviews/form' %>
<% else %>
  <%= link_to "Please sign in.", new_session_path %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price in dollars</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price_in_dollars %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price in cents:</b>
  <%= product_price @product %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

<%= render :partial => 'reviews' %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>User</th>
    <th>Product</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.user %></td>
    <td><%= review.product %></td>
    <td><%= review.comment %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @review.user %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>



<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>


<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label 'name' %>
    <%= f.text_field 'name' %>
  </div>
  <div class="field">
    <%= f.label 'email' %>
    <%= f.text_field 'email' %>
  </div>
  <div class="field">
    <%= f.label 'password' %>
    <%= f.password_field 'password' %>
  </div>
  <div class="field">
    <%= f.label 'password_confirmation' %>
    <%= f.password_field 'password_confirmation' %>
  </div>
  <div class="field">
    <%= f.submit "Sign up!" %>
  </div>
<% end %>